apiVersion: v1
kind: Service
metadata:
  name: wine-ml-service
spec:
  selector:
    app: wine-ml-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort